---
services:
  mini-qr:
    image: ghcr.io/lyqht/mini-qr:latest
    container_name: mini-qr
    restart: unless-stopped
    ports:
      - "3030:8080"
    environment:
      - BASE_PATH=/
      - VITE_HIDE_CREDITS=false
    networks:
      - mini-qr-network

networks:
  mini-qr-network:
    driver: bridge
