# ==================== PROMETHEUS CONFIGURATION ====================
# BeautyCita Monitoring Configuration
# Comprehensive metrics collection for production monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'production'
    project: 'beautycita'

# Rule files
rule_files:
  - "rules/*.yml"

# Alert manager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Scrape configurations
scrape_configs:
  # ==================== PROMETHEUS SELF-MONITORING ====================
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # ==================== NODE EXPORTER ====================
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # ==================== BEAUTYCITA BACKEND ====================
  - job_name: 'beautycita-backend'
    static_configs:
      - targets: ['172.17.0.1:4000']
    scrape_interval: 15s
    metrics_path: /api/metrics
    scrape_timeout: 10s

  # ==================== NGINX EXPORTER ====================
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['172.17.0.1:9113']
    scrape_interval: 15s
    metrics_path: /metrics

  # ==================== POSTGRES EXPORTER ====================
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['172.17.0.1:9187']
    scrape_interval: 30s
    metrics_path: /metrics

  # ==================== REDIS EXPORTER ====================
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['172.17.0.1:9121']
    scrape_interval: 15s
    metrics_path: /metrics

  # ==================== CADVISOR (CONTAINER METRICS) ====================
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s
    metrics_path: /metrics

  # ==================== BLACKBOX EXPORTER (ENDPOINT MONITORING) ====================
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://beautycita.com
        - https://beautycita.com/health
        - https://api.beautycita.com/health
        - https://beautycita.com/api/services
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # ==================== SSL CERTIFICATE MONITORING ====================
  - job_name: 'blackbox-ssl'
    metrics_path: /probe
    params:
      module: [tcp_connect]
    static_configs:
      - targets:
        - beautycita.com:443
        - api.beautycita.com:443
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # ==================== CUSTOM APPLICATION METRICS ====================
  - job_name: 'beautycita-custom-metrics'
    static_configs:
      - targets: ['172.17.0.1:4000']
    scrape_interval: 30s
    metrics_path: /api/metrics
    honor_labels: true
    params:
      format: ['prometheus']

  # ==================== BUSINESS METRICS ====================
  - job_name: 'beautycita-business-metrics'
    static_configs:
      - targets: ['172.17.0.1:4000']
    scrape_interval: 60s
    metrics_path: /api/metrics/business
    honor_labels: true
    params:
      format: ['prometheus']

  # ==================== EXTERNAL DEPENDENCIES ====================
  # Note: These endpoints require authentication and will show as down
  # The actual API integrations work fine when called with proper credentials
  # Consider removing or adding auth-aware health checks
  #- job_name: 'external-apis'
  #  metrics_path: /probe
  #  params:
  #    module: [http_2xx]
  #  static_configs:
  #    - targets:
  #      - https://api.stripe.com/v1/account
  #      - https://maps.googleapis.com
  #      - https://api.anthropic.com
  #  relabel_configs:
  #    - source_labels: [__address__]
  #      target_label: __param_target
  #    - source_labels: [__param_target]
  #      target_label: instance
  #    - target_label: __address__
  #      replacement: blackbox-exporter:9115
  #  scrape_interval: 60s

# ==================== REMOTE WRITE (for long-term storage) ====================
# Uncomment and configure for remote storage
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint.com/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"

# ==================== REMOTE READ ====================
# Uncomment and configure for remote read
# remote_read:
#   - url: "https://prometheus-remote-read-endpoint.com/api/v1/read"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"