#!/bin/bash

# BeautyCita Debug Console Information
# Quick access to monitoring and debugging tools

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  🔍 BeautyCita Debug Console & Monitoring Tools"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📊 GRAFANA DEBUG CONSOLE (Main Interface)"
echo ""
echo "   🌐 PRIMARY ACCESS (Works Everywhere - Standard HTTPS Port):"
echo "      https://beautycita.com/debug/login"
echo ""
echo "      Username: admin"
echo "      Password: BeautyCita2025!"
echo ""
echo "   📊 After Login, Dashboard at:"
echo "      https://beautycita.com/debug/d/7ccc696f-bdfb-4b09-aa29-52d6e8013074/beautycita-debug-console"
echo ""
echo "   🔧 ALTERNATIVE (Port 3001 - May be blocked by some networks):"
echo "      https://beautycita.com:3001/login"
echo ""
echo "   Features:"
echo "   ✓ Live application logs with filtering"
echo "   ✓ Error log viewer (real-time)"
echo "   ✓ Nginx access logs"
echo "   ✓ CPU/Memory/Disk/Network metrics"
echo "   ✓ Auto-refresh every 5 seconds"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🔧 OTHER MONITORING ENDPOINTS"
echo ""
echo "📝 Loki (Log Aggregation)"
echo "   URL: http://YOUR_SERVER_IP:3100"
echo "   Status: $(systemctl is-active loki)"
echo ""
echo "📈 Prometheus (Metrics)"
echo "   URL: http://YOUR_SERVER_IP:9090"
echo "   Status: $(systemctl is-active prometheus)"
echo ""
echo "🚀 Promtail (Log Shipper)"
echo "   URL: http://YOUR_SERVER_IP:9080/targets"
echo "   Status: $(systemctl is-active promtail)"
echo ""
echo "💻 Node Exporter (System Metrics)"
echo "   URL: http://YOUR_SERVER_IP:9100/metrics"
echo "   Status: $(systemctl is-active node_exporter)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 QUICK COMMANDS"
echo ""
echo "  View logs:           sudo -u www-data pm2 logs beautycita-api"
echo "  Restart backend:     sudo -u www-data pm2 restart beautycita-api"
echo "  Check services:      systemctl status loki prometheus grafana-server"
echo "  Grafana reset pass:  grafana-cli admin reset-admin-password <newpass>"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
