-- Insert stylist profiles for Puerto Vallarta with correct user IDs and schema
INSERT INTO stylists (
    user_id,
    business_name,
    bio,
    specialties,
    experience_years,
    certifications,
    social_media_links,
    location_address,
    location_city,
    location_state,
    location_zip,
    location_coordinates,
    pricing_tier,
    is_verified,
    portfolio_published,
    base_price_range
) VALUES
-- Isabella Moreno (ID 120)
(120, 'Bella Studio',
'Especialista en coloración y tratamientos capilares con 8 años de experiencia. Me apasiona crear looks únicos que resalten la belleza natural de cada cliente.',
ARRAY['Coloración', 'Tratamientos capilares', 'Cortes modernos'],
8,
ARRAY['Certificación L''Oréal Professional', 'Colorista Avanzada'],
'{"instagram": "@bella_studio_pv", "facebook": "Bella Studio Puerto Vallarta"}',
'Av. Francisco Villa 1749, Zona Hotelera Norte',
'Puerto Vallarta',
'Jalisco',
'48333',
'(20.6534, -105.2253)',
'PREMIUM',
true,
true,
'$800-1500 MXN'),

-- Sofia Ramirez (ID 121)
(121, 'Sofia Beauty Bar',
'Maquillista profesional especializada en novias y eventos especiales. Creo looks que perduran todo el día con técnicas de maquillaje editorial.',
ARRAY['Maquillaje de novias', 'Eventos especiales', 'Maquillaje editorial'],
6,
ARRAY['MAC Pro Artist', 'Certificación en Airbrush'],
'{"instagram": "@sofia_beauty_pv", "facebook": "Sofia Beauty Bar"}',
'Calle Libertad 348, Centro',
'Puerto Vallarta',
'Jalisco',
'48300',
'(20.6096, -105.2292)',
'LUXURY',
true,
true,
'$1200-2000 MXN'),

-- Camila Gonzalez (ID 122)
(122, 'Camila Nail Studio',
'Nail artist con especialización en diseños únicos y nail art. Trabajo con productos de alta calidad y técnicas innovadoras.',
ARRAY['Nail art', 'Manicura rusa', 'Uñas de gel'],
5,
ARRAY['Certificación en Nail Art', 'Técnicas Rusas Avanzadas'],
'{"instagram": "@camila_nails_pv", "facebook": "Camila Nail Studio"}',
'Calle Hidalgo 123, Centro Histórico',
'Puerto Vallarta',
'Jalisco',
'48300',
'(20.6097, -105.2342)',
'MID_RANGE',
true,
true,
'$400-800 MXN'),

-- Valentina Lopez (ID 123)
(123, 'Valentina Spa & Beauty',
'Esteticista integral con enfoque en tratamientos faciales anti-edad y rejuvenecimiento. Combino técnicas tradicionales con tecnología moderna.',
ARRAY['Tratamientos faciales', 'Anti-edad', 'Limpieza profunda'],
7,
ARRAY['Esteticista Certificada', 'Especialista en Hidrafacial'],
'{"instagram": "@valentina_spa_pv", "facebook": "Valentina Spa & Beauty"}',
'Blvd. Francisco Medina Ascencio 2485, Zona Hotelera',
'Puerto Vallarta',
'Jalisco',
'48333',
'(20.6421, -105.2108)',
'LUXURY',
true,
true,
'$1000-1800 MXN'),

-- Lucia Martinez (ID 124)
(124, 'Lucia Hair Design',
'Estilista especializada en cortes pixie y estilos vanguardistas. Me encanta transformar el look de mis clientas con cortes modernos.',
ARRAY['Cortes pixie', 'Estilos vanguardistas', 'Color fantasía'],
9,
ARRAY['Master Stylist', 'Especialista en Cortes Modernos'],
'{"instagram": "@lucia_hair_pv", "facebook": "Lucia Hair Design"}',
'Calle Corona 115, Zona Romántica',
'Puerto Vallarta',
'Jalisco',
'48380',
'(20.6034, -105.2372)',
'PREMIUM',
true,
true,
'$700-1400 MXN'),

-- Ximena Garcia (ID 125)
(125, 'Ximena Brow Studio',
'Especialista en cejas y micropigmentación. Creo cejas perfectas que enmarcan y realzan la mirada natural de cada rostro.',
ARRAY['Micropigmentación', 'Diseño de cejas', 'Laminado de cejas'],
4,
ARRAY['Certificación en Micropigmentación', 'Brow Artist Professional'],
'{"instagram": "@ximena_brows_pv", "facebook": "Ximena Brow Studio"}',
'Av. Fluvial Vallarta 282, Fluvial Vallarta',
'Puerto Vallarta',
'Jalisco',
'48312',
'(20.6234, -105.2156)',
'MID_RANGE',
true,
true,
'$500-900 MXN'),

-- Regina Rodriguez (ID 126)
(126, 'Regina Glamour',
'Maquillista y peinadora profesional para bodas y quinceañeras. Especializada en looks románticos y elegantes.',
ARRAY['Peinados de novia', 'Maquillaje romántico', 'Eventos sociales'],
6,
ARRAY['Wedding Specialist', 'Certificación en Peinados'],
'{"instagram": "@regina_glamour_pv", "facebook": "Regina Glamour Studio"}',
'Calle 31 de Octubre 246, 5 de Diciembre',
'Puerto Vallarta',
'Jalisco',
'48350',
'(20.6189, -105.2045)',
'PREMIUM',
true,
true,
'$900-1600 MXN'),

-- Fernanda Hernandez (ID 127)
(127, 'Fer Beauty Lounge',
'Cosmetóloga especializada en tratamientos corporales y relajación. Ofrezco una experiencia completa de bienestar.',
ARRAY['Masajes relajantes', 'Tratamientos corporales', 'Aromaterapia'],
8,
ARRAY['Cosmetóloga Certificada', 'Terapeuta en Masajes'],
'{"instagram": "@fer_beauty_pv", "facebook": "Fer Beauty Lounge"}',
'Calle Aquiles Serdán 133, Emiliano Zapata',
'Puerto Vallarta',
'Jalisco',
'48380',
'(20.6098, -105.2289)',
'MID_RANGE',
true,
true,
'$600-1200 MXN'),

-- Daniela Jimenez (ID 128)
(128, 'Dani Color Studio',
'Colorista experta en técnicas de balayage y mechas californianas. Me especializo en rubios naturales y colores vibrantes.',
ARRAY['Balayage', 'Mechas californianas', 'Coloración creativa'],
5,
ARRAY['Balayage Specialist', 'Color Correction Expert'],
'{"instagram": "@dani_color_pv", "facebook": "Dani Color Studio"}',
'Calle Francisca Rodríguez 168, Centro',
'Puerto Vallarta',
'Jalisco',
'48300',
'(20.6145, -105.2298)',
'PREMIUM',
true,
true,
'$800-1500 MXN'),

-- Paulina Vasquez (ID 129)
(129, 'Paulina Lash Studio',
'Especialista en extensiones de pestañas y lifting de pestañas. Creo miradas impactantes con técnicas rusas y volumen.',
ARRAY['Extensiones de pestañas', 'Lash lifting', 'Volumen ruso'],
3,
ARRAY['Lash Artist Certified', 'Russian Volume Technique'],
'{"instagram": "@paulina_lashes_pv", "facebook": "Paulina Lash Studio"}',
'Av. México 1230, 5 de Diciembre',
'Puerto Vallarta',
'Jalisco',
'48350',
'(20.6167, -105.2089)',
'MID_RANGE',
true,
true,
'$400-700 MXN'),

-- Mariana Torres (ID 130)
(130, 'Mari Skin Care',
'Especialista en cuidado de la piel con tratamientos personalizados. Me enfoco en la salud dermatológica y la belleza natural.',
ARRAY['Cuidado de la piel', 'Acné', 'Tratamientos personalizados'],
7,
ARRAY['Dermatocosmiatría', 'Especialista en Acné'],
'{"instagram": "@mari_skincare_pv", "facebook": "Mari Skin Care Clinic"}',
'Calle Juárez 522, Centro',
'Puerto Vallarta',
'Jalisco',
'48300',
'(20.6112, -105.2318)',
'PREMIUM',
true,
true,
'$700-1300 MXN'),

-- Andrea Flores (ID 131)
(131, 'Andrea Style',
'Estilista integral especializada en cambios de look completos. Ofrezco asesoramiento de imagen y transformaciones.',
ARRAY['Cambios de look', 'Asesoramiento de imagen', 'Corte y color'],
6,
ARRAY['Image Consultant', 'Complete Makeover Specialist'],
'{"instagram": "@andrea_style_pv", "facebook": "Andrea Style Studio"}',
'Calle Aldama 150, Zona Romántica',
'Puerto Vallarta',
'Jalisco',
'48380',
'(20.6045, -105.2356)',
'LUXURY',
true,
true,
'$1100-2000 MXN'),

-- Carolina Pena (ID 132)
(132, 'Caro Beauty Room',
'Especialista en tratamientos faciales y rejuvenecimiento. Utilizo tecnología de punta para resultados visibles.',
ARRAY['Radiofrecuencia', 'Tratamientos anti-edad', 'Hidratación profunda'],
9,
ARRAY['Tecnología Estética', 'Anti-aging Specialist'],
'{"instagram": "@caro_beauty_pv", "facebook": "Caro Beauty Room"}',
'Av. de los Tules 136, Aramara',
'Puerto Vallarta',
'Jalisco',
'48313',
'(20.6298, -105.2134)',
'LUXURY',
true,
true,
'$1200-2200 MXN'),

-- Michelle Castro (ID 133)
(133, 'Michelle Nails & More',
'Nail artist y especialista en pedicura spa. Creo diseños únicos y ofrezco tratamientos relajantes para manos y pies.',
ARRAY['Pedicura spa', 'Diseños creativos', 'Cuidado de manos'],
4,
ARRAY['Spa Pedicure Specialist', 'Creative Nail Design'],
'{"instagram": "@michelle_nails_pv", "facebook": "Michelle Nails & More"}',
'Calle Miramar 336, Versalles',
'Puerto Vallarta',
'Jalisco',
'48310',
'(20.6256, -105.2198)',
'MID_RANGE',
true,
true,
'$350-650 MXN'),

-- Alejandra Ruiz (ID 134)
(134, 'Ale Hair Boutique',
'Estilista especializada en cabello rizado y tratamientos de alisado. Experta en cuidado específico para cada tipo de cabello.',
ARRAY['Cabello rizado', 'Alisados', 'Tratamientos capilares'],
8,
ARRAY['Curly Hair Specialist', 'Keratin Treatment Expert'],
'{"instagram": "@ale_hair_pv", "facebook": "Ale Hair Boutique"}',
'Calle Brasil 1240, 5 de Diciembre',
'Puerto Vallarta',
'Jalisco',
'48350',
'(20.6178, -105.2067)',
'PREMIUM',
true,
true,
'$750-1400 MXN'),

-- Natalia Mendoza (ID 135)
(135, 'Nat Makeup Studio',
'Maquillista especializada en fotografía y video. Creo looks que se ven perfectos tanto en persona como en cámara.',
ARRAY['Maquillaje para fotografía', 'Video makeup', 'Eventos corporativos'],
5,
ARRAY['Photography Makeup Artist', 'HD Makeup Specialist'],
'{"instagram": "@nat_makeup_pv", "facebook": "Nat Makeup Studio"}',
'Calle Venustiano Carranza 445, Centro',
'Puerto Vallarta',
'Jalisco',
'48300',
'(20.6089, -105.2334)',
'PREMIUM',
true,
true,
'$800-1500 MXN'),

-- Paola Aguilar (ID 136)
(136, 'Paola Wellness Spa',
'Terapeuta holística especializada en masajes terapéuticos y relajación profunda. Combino técnicas orientales y occidentales.',
ARRAY['Masajes terapéuticos', 'Reflexología', 'Relajación profunda'],
7,
ARRAY['Terapeuta Holística', 'Reflexology Certified'],
'{"instagram": "@paola_wellness_pv", "facebook": "Paola Wellness Spa"}',
'Av. Francisco Villa 799, Zona Hotelera Norte',
'Puerto Vallarta',
'Jalisco',
'48333',
'(20.6456, -105.2189)',
'LUXURY',
true,
true,
'$1000-1800 MXN'),

-- Karla Morales (ID 137)
(137, 'Karla Beauty Lab',
'Especialista en pestañas y cejas con técnicas innovadoras. Ofrezco servicios de laminado, tinte y diseño personalizado.',
ARRAY['Laminado de cejas', 'Tinte de pestañas', 'Diseño personalizado'],
6,
ARRAY['Brow & Lash Specialist', 'Lamination Expert'],
'{"instagram": "@karla_beauty_pv", "facebook": "Karla Beauty Lab"}',
'Calle Iturbide 377, Centro',
'Puerto Vallarta',
'Jalisco',
'48300',
'(20.6123, -105.2287)',
'MID_RANGE',
true,
true,
'$450-750 MXN'),

-- Gabriela Ortiz (ID 138)
(138, 'Gaby Color House',
'Colorista creativa especializada en colores fantasía y técnicas de decoloración segura. Me encanta crear looks únicos y vibrantes.',
ARRAY['Colores fantasía', 'Decoloración', 'Looks creativos'],
4,
ARRAY['Fantasy Color Expert', 'Bleaching Specialist'],
'{"instagram": "@gaby_color_pv", "facebook": "Gaby Color House"}',
'Calle Morelos 660, Centro',
'Puerto Vallarta',
'Jalisco',
'48300',
'(20.6067, -105.2301)',
'MID_RANGE',
true,
true,
'$600-1100 MXN'),

-- Valeria Delgado (ID 139)
(139, 'Vale Glam Studio',
'Maquillista y estilista integral para eventos especiales. Especializada en quinceañeras y graduaciones con estilos juveniles.',
ARRAY['Quinceañeras', 'Graduaciones', 'Estilos juveniles'],
5,
ARRAY['Special Events Makeup', 'Youth Style Specialist'],
'{"instagram": "@vale_glam_pv", "facebook": "Vale Glam Studio"}',
'Av. Insurgentes 1456, Insurgentes',
'Puerto Vallarta',
'Jalisco',
'48340',
'(20.6201, -105.2023)',
'PREMIUM',
true,
true,
'$850-1600 MXN');