name: Deploy to Production

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd /var/www/beautycita.com

            # Pull latest changes
            git pull origin master

            # Backend updates
            cd backend
            sudo -u www-data npm install --production
            sudo -u www-data pm2 restart beautycita-api

            # Frontend build
            cd ../frontend
            sudo -u www-data npm install
            sudo -u www-data npm run build

            # Reload nginx
            sudo systemctl reload nginx

            # Verify deployment
            sleep 5
            curl -f https://beautycita.com/api/health || exit 1

            echo "✅ Deployment successful"
